In [1]:
# import pip

# def install(package):
#     if hasattr(pip, 'main'):
#         pip.main(['install', package])
#     else:
#         pip._internal.main(['install', package])

# # Example
# install('scikit-learn')

In [2]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [3]:
# pd.np.set_printoptions(suppress=True)

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('jan20_01-21_000000-235959.csv')

/usr/local/Cellar/jupyterlab/3.0.12/libexec/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (29) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [6]:
df = df[['rt_author_id', 't_author_id', 'rt_text', 't_text']]

In [7]:
df

rt_author_id   t_author_id  \
0                  28967452  2.802593e+07   
1                  57283792  1.665058e+08   
2                 211845768  2.261946e+08   
3                 119321075  9.541244e+08   
4                1391090496  9.541244e+08   
...                     ...           ...   
782916  1148252342048952322  9.070342e+17   
782917             23948496           NaN   
782918            306412670           NaN   
782919            632909553  9.070342e+17   
782920            352051593           NaN   

                                                  rt_text  \
0       RT @vmyths: FYI, I'm going to drive home on Fl...   
1         @ardnif Dindin kebanjiran?? Staysafe yaaa Din 😘   
2       Except you can’t sue vaccine manufacturers htt...   
3       RT @AmyMek: Happy New Year from Sharia Sweden....   
4       RT @AmyMek: Happy New Year from Sharia Sweden....   
...                                                   ...   
782916  RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...   
782917  A resident of West Courthouse Road found Coope...   
782918  #Zambia has 17 million people, a stroke epidem...   
782919  RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...   
782920  四種混合（百日せき、ジフテリア、破傷風、ポリオ）予防接種の接種対象年齢は、生後３か月から90...   

                                                   t_text  
0       FYI, I'm going to drive home on Florida's Turn...  
1       isi powerbank cuma pas mau ngonser atau pergi ...  
2       Just heard a medicine commercial say “If you h...  
3       Happy New Year from Sharia Sweden...\n\n'Gang ...  
4       Happy New Year from Sharia Sweden...\n\n'Gang ...  
...                                                   ...  
782916  ——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...  
782917                                                NaN  
782918                                                NaN  
782919  ——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...  
782920                                                NaN  

[782921 rows x 4 columns]

In [8]:
# df.rt_ref_tweet_id.fillna(0).apply(int)

In [9]:
df.t_text[0]

"FYI, I'm going to drive home on Florida's Turnpike with a code that QR-enabled license plate readers will log in their ASCII databases ... which could trigger #antivirus software to QUARANTINE those databases 🥳 https://t.co/L2sYfgIxUH"

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer(analyzer='word',token_pattern=r'[\w\@\#]+')

In [12]:
vec = cv.fit_transform(df.rt_text.dropna().to_numpy())

In [13]:
# df.rt_text.dropna()

In [14]:
# df.rt_text.dropna().to_numpy()

In [15]:
# vec[:,0].toarray()

In [16]:
'covid' in cv.get_feature_names()

True

In [17]:
# with open('cv.txt', 'w') as f:
#     f.write("\n".join(cv.get_feature_names()))

In [18]:
kwl = ['covid', 'corona', 'coronavirus','coronavirus#health']

In [19]:
kwi = [cv.get_feature_names().index(kw) for kw in kwl]

In [20]:
# print(dir(kwl))

In [21]:
# cv.get_feature_names().index('coronavirus')

In [22]:
# cv.get_feature_names()[90943]

In [23]:
data = vec[:,kwi]

In [24]:
# data.toarray()

In [25]:
df['coronavirus'] = data[:,2].toarray()

In [26]:
# len(cv.get_feature_names())

In [27]:
# data[:,0].sum() ## from column

In [28]:
# data[100].toarray()

In [29]:
df[data[:,2].toarray()>0]

rt_author_id   t_author_id  \
352              1352962327  4.437650e+07   
412                44376499  4.437650e+07   
1764             1094778392  8.467996e+17   
2490              313770528  8.467996e+17   
2518              275504280  8.467996e+17   
...                     ...           ...   
772310   732787392722182144  7.327874e+17   
772441            392357015           NaN   
773775           3091462193  4.416085e+09   
775452  1035067362003824640  3.112422e+09   
780657           4349427974           NaN   

                                                  rt_text  \
352     RT @PeterDaszak: @ProMED_mail Still waiting on...   
412     @ProMED_mail Still waiting on news from China....   
1764    RT @chairvaccines: Middle East respiratory syn...   
2490    RT @chairvaccines: Middle East respiratory syn...   
2518    RT @chairvaccines: Middle East respiratory syn...   
...                                                   ...   
772310  RT @DelthiaRicks: Novel coronavirus: While cam...   
772441  Cryo-EM analysis of a feline coronavirus spike...   
773775  RT @joostsnijder: Cryo-EM analysis of a feline...   
775452  RT @intelOverwatch: Wuhan disease human transm...   
780657  What Is Equine Coronavirus? https://t.co/hb9R6...   

                                                   t_text  coronavirus  
352     @ProMED_mail Still waiting on news from China....            1  
412     There is some important and disturbing informa...            1  
1764    Middle East respiratory syndrome (MERS) is a v...            1  
2490    Middle East respiratory syndrome (MERS) is a v...            1  
2518    Middle East respiratory syndrome (MERS) is a v...            1  
...                                                   ...          ...  
772310  Novel coronavirus: While camels are the reserv...            2  
772441                                                NaN            1  
773775  Cryo-EM analysis of a feline coronavirus spike...            1  
775452  Wuhan disease human transmission not ruled out...            1  
780657                                                NaN            1  

[167128 rows x 5 columns]

In [30]:
df

rt_author_id   t_author_id  \
0                  28967452  2.802593e+07   
1                  57283792  1.665058e+08   
2                 211845768  2.261946e+08   
3                 119321075  9.541244e+08   
4                1391090496  9.541244e+08   
...                     ...           ...   
782916  1148252342048952322  9.070342e+17   
782917             23948496           NaN   
782918            306412670           NaN   
782919            632909553  9.070342e+17   
782920            352051593           NaN   

                                                  rt_text  \
0       RT @vmyths: FYI, I'm going to drive home on Fl...   
1         @ardnif Dindin kebanjiran?? Staysafe yaaa Din 😘   
2       Except you can’t sue vaccine manufacturers htt...   
3       RT @AmyMek: Happy New Year from Sharia Sweden....   
4       RT @AmyMek: Happy New Year from Sharia Sweden....   
...                                                   ...   
782916  RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...   
782917  A resident of West Courthouse Road found Coope...   
782918  #Zambia has 17 million people, a stroke epidem...   
782919  RT @AesopsFableFly: ——— BTS LOCKDOWN ———\n\nwh...   
782920  四種混合（百日せき、ジフテリア、破傷風、ポリオ）予防接種の接種対象年齢は、生後３か月から90...   

                                                   t_text  coronavirus  
0       FYI, I'm going to drive home on Florida's Turn...            0  
1       isi powerbank cuma pas mau ngonser atau pergi ...            0  
2       Just heard a medicine commercial say “If you h...            0  
3       Happy New Year from Sharia Sweden...\n\n'Gang ...            0  
4       Happy New Year from Sharia Sweden...\n\n'Gang ...            0  
...                                                   ...          ...  
782916  ——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...            0  
782917                                                NaN            0  
782918                                                NaN            0  
782919  ——— BTS LOCKDOWN ———\n\nwhat is a bts lockdown...            0  
782920                                                NaN            0  

[782921 rows x 5 columns]

In [31]:
vec.sum(axis=0)

matrix([[1650,    7,    1, ...,    1,    1,    1]])

In [32]:
# np.array([[1,2],[1,2]]).sum(axis=1)

In [33]:
labels = cv.get_feature_names()

In [34]:
mentions = []
mention_indicies = []
hashtags = []
hashtag_indicies = []

for i, v in enumerate(labels):
    if v.startswith('@'):
        mentions.append(v)
        mention_indicies.append(i)
    elif v.startswith('#'):
        hashtags.append(v)
        hashtag_indicies.append(i)

In [67]:
len(mentions)

100741

In [36]:
# np.array(mentions)[[0,1]]

In [37]:
mentions = np.array(mentions)
mention_indicies = np.array(mention_indicies)
hashtags = np.array(hashtags)
hashtag_indicies = np.array(hashtag_indicies)

In [62]:
mention_vec = vec[:,mention_indicies]
hashtag_vec = vec[:,hashtag_indicies]

In [92]:
mentions_count = np.array(mention_vec.sum(axis=0)).flatten()
mentions_rank_indicies = mentions_count.argsort()[::-1]

In [64]:
mentions_ranked = mentions[mentions_rank_indicies]

In [79]:
top10mentions = mentions_ranked.tolist()[::-1][:10]

In [95]:
top10mentions_vec = vec[:,mention_indicies[mentions_rank_indicies[:10]]].toarray()

In [98]:
df['who'] = top10mentions_vec[:,0]

In [100]:
df[df.who>0]

rt_author_id   t_author_id  \
2111              488292054  1.954403e+09   
3280    1105064943794245632  1.415915e+07   
4881             2476070574  1.174222e+18   
5096              426776226  1.449983e+07   
5490    1183658840077680640  1.174222e+18   
...                     ...           ...   
772199           3293886549           NaN   
772214              7587032           NaN   
774033           4784948594  2.919391e+09   
775518           1173286656  7.039767e+17   
775866   703976714704007169           NaN   

                                                  rt_text  \
2111    @thecableng @WHO @nighealthwatch @DrOlufunmila...   
3280    @UN @WHO Yup but Kashmir issues where are you?...   
4881    RT @TBG9270584: Maine Puts Vaccine Mandates to...   
5096    RT @WHO: It's World Immunization Week! \n\nVac...   
5490    RT @TBG9270584: Maine Puts Vaccine Mandates to...   
...                                                   ...   
772199  The death toll from a measles epidemic in the ...   
772214  The death toll from a measles epidemic in the ...   
774033  @cmohry @PMOIndia @narendramodi @mlkhattar @WH...   
775518  RT @scleroplex: One more detailed report from ...   
775866  One more detailed report from @HelenBranswell ...   

                                                   t_text  coronavirus  who  
2111    TheCable names Stella Adadevoh as ‘Nigerian of...            0    1  
3280    As you start a new year, check out these 12 ti...            0    1  
4881    Maine Puts Vaccine Mandates to a Popular Vote ...            0    1  
5096    It's World Immunization Week! \n\nVaccine-prev...            0    1  
5490    Maine Puts Vaccine Mandates to a Popular Vote ...            0    1  
...                                                   ...          ...  ...  
772199                                                NaN            0    1  
772214                                                NaN            0    1  
774033  @dpkchnindia Please share your contact number ...            0    1  
775518  One more detailed report from @HelenBranswell ...            0    1  
775866                                                NaN            0    1  

[23740 rows x 6 columns]

In [97]:
df[] = df[top10mentions_vec[:,0]>0]

rt_author_id   t_author_id  \
2111              488292054  1.954403e+09   
3280    1105064943794245632  1.415915e+07   
4881             2476070574  1.174222e+18   
5096              426776226  1.449983e+07   
5490    1183658840077680640  1.174222e+18   
...                     ...           ...   
772199           3293886549           NaN   
772214              7587032           NaN   
774033           4784948594  2.919391e+09   
775518           1173286656  7.039767e+17   
775866   703976714704007169           NaN   

                                                  rt_text  \
2111    @thecableng @WHO @nighealthwatch @DrOlufunmila...   
3280    @UN @WHO Yup but Kashmir issues where are you?...   
4881    RT @TBG9270584: Maine Puts Vaccine Mandates to...   
5096    RT @WHO: It's World Immunization Week! \n\nVac...   
5490    RT @TBG9270584: Maine Puts Vaccine Mandates to...   
...                                                   ...   
772199  The death toll from a measles epidemic in the ...   
772214  The death toll from a measles epidemic in the ...   
774033  @cmohry @PMOIndia @narendramodi @mlkhattar @WH...   
775518  RT @scleroplex: One more detailed report from ...   
775866  One more detailed report from @HelenBranswell ...   

                                                   t_text  coronavirus  
2111    TheCable names Stella Adadevoh as ‘Nigerian of...            0  
3280    As you start a new year, check out these 12 ti...            0  
4881    Maine Puts Vaccine Mandates to a Popular Vote ...            0  
5096    It's World Immunization Week! \n\nVaccine-prev...            0  
5490    Maine Puts Vaccine Mandates to a Popular Vote ...            0  
...                                                   ...          ...  
772199                                                NaN            0  
772214                                                NaN            0  
774033  @dpkchnindia Please share your contact number ...            0  
775518  One more detailed report from @HelenBranswell ...            0  
775866                                                NaN            0  

[23740 rows x 5 columns]

In [86]:
# mention_indicies[mentions_rank_indicies[:-10]].shape

(100731,)

In [93]:
# vec[:,mention_indicies[mentions_rank_indicies[:10]]].toarray().shape

(782921, 10)

In [74]:
mentions_count[mentions_rank_indicies]

array([    1,     1,     1, ..., 11126, 15641, 23809])

In [45]:
a.data

In [51]:
np.array(a)#.flatten()

array([[183,   2,   0, ...,   0,   0,   0]])

In [68]:
hashtags_count = np.array(hashtag_vec.sum(axis=0)).flatten()
hashtags_rank_indicies = hashtags_count.argsort()[::-1]

In [69]:
hashtags_ranked = hashtags[hashtags_rank_indicies]

In [70]:
hashtags_ranked

array(['#toyotabookoflife', '#teachus', '#team100', ..., '#wuhan',
       '#china', '#coronavirus'], dtype='<U169')

In [72]:
hashtags_count[hashtags_rank_indicies]

array([    1,     1,     1, ..., 10394, 18458, 62560])